// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lbZJXbOkWNkgRxvzqwhLtgGQf5GmpS4',
    appId: '1:493010584500:web:9c958f30725cd60533a8e1',
    messagingSenderId: '493010584500',
    projectId: 'universe-fct',
    authDomain: 'universe-fct.firebaseapp.com',
    databaseURL: 'https://universe-fct-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'universe-fct.appspot.com',
    measurementId: 'G-XB1FHSZ4M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU88oAVq67egEovJ90EjhWm1oHL5Ylpm8',
    appId: '1:493010584500:android:771032ce1257f06a33a8e1',
    messagingSenderId: '493010584500',
    projectId: 'universe-fct',
    databaseURL: 'https://universe-fct-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'universe-fct.appspot.com',
  );
}
